name: opencca-build

on:
  push:
    branches:
      - opencca/main
  workflow_dispatch:

concurrency:
  group: schedule-${{ github.workflow }}
  cancel-in-progress: true

env:
  BUILD_SCRIPT: ${{ github.workspace }}/.github/workflows/opencca/opencca-build.sh
  BUILD_SNAPSHOT_DIR: ${{ github.workspace }}/../snapshot


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run build script
        run: |
          cp ./.github/workflows/opencca/run-in-docker.sh ../
          cd ../
          chmod +x run-in-docker.sh
          ./run-in-docker.sh $BUILD_SCRIPT

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tf-rmm-snapshot
          path: $BUILD_SNAPSHOT_DIR/tf-rmm.elf
