name: opencca-build

on:
  push:
    branches:
      - opencca/main
  workflow_dispatch:

concurrency:
  group: schedule-${{ github.workflow }}
  cancel-in-progress: true

env:
  BUILD_SCRIPT: ${{ github.workspace }}/.github/workflows/opencca/opencca-build.sh
  RUNNER_DIR: ${{ github.workspace }}/.runner-build


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run build script
        run: |
          rm -r $RUNNER_DIR || true
          mkdir -p $RUNNER_DIR
          cp ./.github/workflows/opencca/run-in-docker.sh $RUNNER_DIR/
          cd $RUNNER_DIR
          ln -s ../ tf-rmm
          chmod +x run-in-docker.sh
          mkdir -p snapshot

          ./run-in-docker.sh $BUILD_SCRIPT
          ls -al $RUNNER_DIR
          ls -al $RUNNER_DIR/snapshot

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tf-rmm-snapshot
          path: ${{ env.RUNNER_DIR }}/snapshot/tf-rmm.elf
          if-no-files-found: error
